//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skabi.web.mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carmodel
    {
        public carmodel()
        {
            this.carmodeltypes = new HashSet<carmodeltype>();
        }
    
        public int id { get; set; }
        public int carbrand_id { get; set; }
        public string model_name { get; set; }
        public int modelclicks { get; set; }
    
        public virtual carbrand carbrand { get; set; }
        public virtual ICollection<carmodeltype> carmodeltypes { get; set; }
    }
}
