//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skabi.web.mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal
    {
        public proposal()
        {
            this.carmodeltypes_proposals = new HashSet<carmodeltypes_proposals>();
        }
    
        public int id { get; set; }
        public string art_nr { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string depth { get; set; }
        public string weight { get; set; }
        public string price { get; set; }
        public string price_installed { get; set; }
        public int proposalclicks { get; set; }
    
        public virtual ICollection<carmodeltypes_proposals> carmodeltypes_proposals { get; set; }
    }
}
