//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace skabi.data.DomainModel
{
    public partial class Carbrand
    {
        #region Primitive Properties
    
        public virtual int CarbrandID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual int Clicks
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Carmodel> Carmodels
        {
            get
            {
                if (_carmodels == null)
                {
                    var newCollection = new FixupCollection<Carmodel>();
                    newCollection.CollectionChanged += FixupCarmodels;
                    _carmodels = newCollection;
                }
                return _carmodels;
            }
            set
            {
                if (!ReferenceEquals(_carmodels, value))
                {
                    var previousValue = _carmodels as FixupCollection<Carmodel>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCarmodels;
                    }
                    _carmodels = value;
                    var newValue = value as FixupCollection<Carmodel>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCarmodels;
                    }
                }
            }
        }
        private ICollection<Carmodel> _carmodels;

        #endregion

        #region Association Fixup
    
        private void FixupCarmodels(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Carmodel item in e.NewItems)
                {
                    item.Carbrand = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Carmodel item in e.OldItems)
                {
                    if (ReferenceEquals(item.Carbrand, this))
                    {
                        item.Carbrand = null;
                    }
                }
            }
        }

        #endregion

    }
}
