//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace skabi.data.DomainModel
{
    public partial class Carmodel
    {
        #region Primitive Properties
    
        public virtual int CarmodelID
        {
            get;
            set;
        }
    
        public virtual int CarbrandID
        {
            get { return _carbrandID; }
            set
            {
                if (_carbrandID != value)
                {
                    if (Carbrand != null && Carbrand.CarbrandID != value)
                    {
                        Carbrand = null;
                    }
                    _carbrandID = value;
                }
            }
        }
        private int _carbrandID;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual int Clicks
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Carbrand Carbrand
        {
            get { return _carbrand; }
            set
            {
                if (!ReferenceEquals(_carbrand, value))
                {
                    var previousValue = _carbrand;
                    _carbrand = value;
                    FixupCarbrand(previousValue);
                }
            }
        }
        private Carbrand _carbrand;
    
        public virtual ICollection<CarmodelType> CarmodelTypes
        {
            get
            {
                if (_carmodelTypes == null)
                {
                    var newCollection = new FixupCollection<CarmodelType>();
                    newCollection.CollectionChanged += FixupCarmodelTypes;
                    _carmodelTypes = newCollection;
                }
                return _carmodelTypes;
            }
            set
            {
                if (!ReferenceEquals(_carmodelTypes, value))
                {
                    var previousValue = _carmodelTypes as FixupCollection<CarmodelType>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCarmodelTypes;
                    }
                    _carmodelTypes = value;
                    var newValue = value as FixupCollection<CarmodelType>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCarmodelTypes;
                    }
                }
            }
        }
        private ICollection<CarmodelType> _carmodelTypes;

        #endregion

        #region Association Fixup
    
        private void FixupCarbrand(Carbrand previousValue)
        {
            if (previousValue != null && previousValue.Carmodels.Contains(this))
            {
                previousValue.Carmodels.Remove(this);
            }
    
            if (Carbrand != null)
            {
                if (!Carbrand.Carmodels.Contains(this))
                {
                    Carbrand.Carmodels.Add(this);
                }
                if (CarbrandID != Carbrand.CarbrandID)
                {
                    CarbrandID = Carbrand.CarbrandID;
                }
            }
        }
    
        private void FixupCarmodelTypes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CarmodelType item in e.NewItems)
                {
                    item.Carmodel = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CarmodelType item in e.OldItems)
                {
                    if (ReferenceEquals(item.Carmodel, this))
                    {
                        item.Carmodel = null;
                    }
                }
            }
        }

        #endregion

    }
}
