//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace skabi.data.DomainModel
{
    public partial class CarmodelType
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual int carmodel_id
        {
            get { return _carmodel_id; }
            set
            {
                if (_carmodel_id != value)
                {
                    if (Carmodel != null && Carmodel.id != value)
                    {
                        Carmodel = null;
                    }
                    _carmodel_id = value;
                }
            }
        }
        private int _carmodel_id;
    
        public virtual int wheelbase
        {
            get;
            set;
        }
    
        public virtual string cubic
        {
            get;
            set;
        }
    
        public virtual int typeclicks
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Carmodel Carmodel
        {
            get { return _carmodel; }
            set
            {
                if (!ReferenceEquals(_carmodel, value))
                {
                    var previousValue = _carmodel;
                    _carmodel = value;
                    FixupCarmodel(previousValue);
                }
            }
        }
        private Carmodel _carmodel;
    
        public virtual ICollection<CarmodelTypesProposal> CarmodelTypesProposals
        {
            get
            {
                if (_carmodelTypesProposals == null)
                {
                    var newCollection = new FixupCollection<CarmodelTypesProposal>();
                    newCollection.CollectionChanged += FixupCarmodelTypesProposals;
                    _carmodelTypesProposals = newCollection;
                }
                return _carmodelTypesProposals;
            }
            set
            {
                if (!ReferenceEquals(_carmodelTypesProposals, value))
                {
                    var previousValue = _carmodelTypesProposals as FixupCollection<CarmodelTypesProposal>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCarmodelTypesProposals;
                    }
                    _carmodelTypesProposals = value;
                    var newValue = value as FixupCollection<CarmodelTypesProposal>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCarmodelTypesProposals;
                    }
                }
            }
        }
        private ICollection<CarmodelTypesProposal> _carmodelTypesProposals;

        #endregion

        #region Association Fixup
    
        private void FixupCarmodel(Carmodel previousValue)
        {
            if (previousValue != null && previousValue.CarmodelTypes.Contains(this))
            {
                previousValue.CarmodelTypes.Remove(this);
            }
    
            if (Carmodel != null)
            {
                if (!Carmodel.CarmodelTypes.Contains(this))
                {
                    Carmodel.CarmodelTypes.Add(this);
                }
                if (carmodel_id != Carmodel.id)
                {
                    carmodel_id = Carmodel.id;
                }
            }
        }
    
        private void FixupCarmodelTypesProposals(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CarmodelTypesProposal item in e.NewItems)
                {
                    item.CarmodelType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CarmodelTypesProposal item in e.OldItems)
                {
                    if (ReferenceEquals(item.CarmodelType, this))
                    {
                        item.CarmodelType = null;
                    }
                }
            }
        }

        #endregion

    }
}
