//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace skabi.data.DomainModel
{
    public partial class CarmodelTypesProposal
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual int carmodeltype_id
        {
            get { return _carmodeltype_id; }
            set
            {
                if (_carmodeltype_id != value)
                {
                    if (CarmodelType != null && CarmodelType.id != value)
                    {
                        CarmodelType = null;
                    }
                    _carmodeltype_id = value;
                }
            }
        }
        private int _carmodeltype_id;
    
        public virtual int proposal_id
        {
            get { return _proposal_id; }
            set
            {
                if (_proposal_id != value)
                {
                    if (Proposal != null && Proposal.id != value)
                    {
                        Proposal = null;
                    }
                    _proposal_id = value;
                }
            }
        }
        private int _proposal_id;
    
        public virtual int left_right
        {
            get;
            set;
        }
    
        public virtual int uniqueclicks
        {
            get;
            set;
        }
    
        public virtual int order_id
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual CarmodelType CarmodelType
        {
            get { return _carmodelType; }
            set
            {
                if (!ReferenceEquals(_carmodelType, value))
                {
                    var previousValue = _carmodelType;
                    _carmodelType = value;
                    FixupCarmodelType(previousValue);
                }
            }
        }
        private CarmodelType _carmodelType;
    
        public virtual Proposal Proposal
        {
            get { return _proposal; }
            set
            {
                if (!ReferenceEquals(_proposal, value))
                {
                    var previousValue = _proposal;
                    _proposal = value;
                    FixupProposal(previousValue);
                }
            }
        }
        private Proposal _proposal;

        #endregion

        #region Association Fixup
    
        private void FixupCarmodelType(CarmodelType previousValue)
        {
            if (previousValue != null && previousValue.CarmodelTypesProposals.Contains(this))
            {
                previousValue.CarmodelTypesProposals.Remove(this);
            }
    
            if (CarmodelType != null)
            {
                if (!CarmodelType.CarmodelTypesProposals.Contains(this))
                {
                    CarmodelType.CarmodelTypesProposals.Add(this);
                }
                if (carmodeltype_id != CarmodelType.id)
                {
                    carmodeltype_id = CarmodelType.id;
                }
            }
        }
    
        private void FixupProposal(Proposal previousValue)
        {
            if (previousValue != null && previousValue.CarmodelTypesProposals.Contains(this))
            {
                previousValue.CarmodelTypesProposals.Remove(this);
            }
    
            if (Proposal != null)
            {
                if (!Proposal.CarmodelTypesProposals.Contains(this))
                {
                    Proposal.CarmodelTypesProposals.Add(this);
                }
                if (proposal_id != Proposal.id)
                {
                    proposal_id = Proposal.id;
                }
            }
        }

        #endregion

    }
}
