//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace skabi.data.DomainModel
{
    public partial class Proposal
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string art_nr
        {
            get;
            set;
        }
    
        public virtual string width
        {
            get;
            set;
        }
    
        public virtual string height
        {
            get;
            set;
        }
    
        public virtual string depth
        {
            get;
            set;
        }
    
        public virtual string weight
        {
            get;
            set;
        }
    
        public virtual string price
        {
            get;
            set;
        }
    
        public virtual string price_installed
        {
            get;
            set;
        }
    
        public virtual int proposalclicks
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CarmodelTypesProposal> CarmodelTypesProposals
        {
            get
            {
                if (_carmodelTypesProposals == null)
                {
                    var newCollection = new FixupCollection<CarmodelTypesProposal>();
                    newCollection.CollectionChanged += FixupCarmodelTypesProposals;
                    _carmodelTypesProposals = newCollection;
                }
                return _carmodelTypesProposals;
            }
            set
            {
                if (!ReferenceEquals(_carmodelTypesProposals, value))
                {
                    var previousValue = _carmodelTypesProposals as FixupCollection<CarmodelTypesProposal>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCarmodelTypesProposals;
                    }
                    _carmodelTypesProposals = value;
                    var newValue = value as FixupCollection<CarmodelTypesProposal>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCarmodelTypesProposals;
                    }
                }
            }
        }
        private ICollection<CarmodelTypesProposal> _carmodelTypesProposals;

        #endregion

        #region Association Fixup
    
        private void FixupCarmodelTypesProposals(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CarmodelTypesProposal item in e.NewItems)
                {
                    item.Proposal = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CarmodelTypesProposal item in e.OldItems)
                {
                    if (ReferenceEquals(item.Proposal, this))
                    {
                        item.Proposal = null;
                    }
                }
            }
        }

        #endregion

    }
}
