//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace skabi.data.DomainModel
{
    public partial class rpdbEntities : ObjectContext
    {
        public const string ConnectionString = "name=rpdbEntities";
        public const string ContainerName = "rpdbEntities";
    
        #region Constructors
    
        public rpdbEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public rpdbEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public rpdbEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Carbrand> Carbrands
        {
            get { return _carbrands  ?? (_carbrands = CreateObjectSet<Carbrand>("Carbrands")); }
        }
        private ObjectSet<Carbrand> _carbrands;
    
        public ObjectSet<Carmodel> Carmodels
        {
            get { return _carmodels  ?? (_carmodels = CreateObjectSet<Carmodel>("Carmodels")); }
        }
        private ObjectSet<Carmodel> _carmodels;
    
        public ObjectSet<CarmodelType> CarmodelTypes
        {
            get { return _carmodelTypes  ?? (_carmodelTypes = CreateObjectSet<CarmodelType>("CarmodelTypes")); }
        }
        private ObjectSet<CarmodelType> _carmodelTypes;
    
        public ObjectSet<CarmodelTypesProposal> CarmodelTypesProposals
        {
            get { return _carmodelTypesProposals  ?? (_carmodelTypesProposals = CreateObjectSet<CarmodelTypesProposal>("CarmodelTypesProposals")); }
        }
        private ObjectSet<CarmodelTypesProposal> _carmodelTypesProposals;
    
        public ObjectSet<News> News
        {
            get { return _news  ?? (_news = CreateObjectSet<News>("News")); }
        }
        private ObjectSet<News> _news;
    
        public ObjectSet<Proposal> Proposals
        {
            get { return _proposals  ?? (_proposals = CreateObjectSet<Proposal>("Proposals")); }
        }
        private ObjectSet<Proposal> _proposals;

        #endregion

    }
}
