//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skabi.mvc.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carbrand
    {
        public carbrand()
        {
            this.carmodels = new HashSet<carmodel>();
        }
    
        public int id { get; set; }
        public string brand_name { get; set; }
        public int brandclicks { get; set; }
    
        public virtual carbrand carbrands1 { get; set; }
        public virtual carbrand carbrand1 { get; set; }
        public virtual ICollection<carmodel> carmodels { get; set; }
    }
}
