//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skabi.mvc.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carmodeltypes_proposals
    {
        public int id { get; set; }
        public int carmodeltype_id { get; set; }
        public int proposal_id { get; set; }
        public int left_right { get; set; }
        public int uniqueclicks { get; set; }
        public int order_id { get; set; }
    
        public virtual carmodeltype carmodeltype { get; set; }
        public virtual proposal proposal { get; set; }
    }
}
