//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skabi.mvc.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carmodeltype
    {
        public carmodeltype()
        {
            this.carmodeltypes_proposals = new HashSet<carmodeltypes_proposals>();
        }
    
        public int id { get; set; }
        public int carmodel_id { get; set; }
        public int wheelbase { get; set; }
        public string cubic { get; set; }
        public int typeclicks { get; set; }
    
        public virtual carmodel carmodel { get; set; }
        public virtual ICollection<carmodeltypes_proposals> carmodeltypes_proposals { get; set; }
    }
}
