//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skabi.mvc.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rpdbEntities : DbContext
    {
        public rpdbEntities()
            : base("name=rpdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carbrand> carbrands { get; set; }
        public DbSet<carmodel> carmodels { get; set; }
        public DbSet<carmodeltype> carmodeltypes { get; set; }
        public DbSet<carmodeltypes_proposals> carmodeltypes_proposals { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<proposal> proposals { get; set; }
    }
}
